server:
  port: 1236
# 数据库配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.127.70:3306/yang-blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # Hikari 连接池配置
    # 最小空闲连接数量
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # 重写配置
  main:
    allow-bean-definition-overriding: true
  transaction:
    rollback-on-commit-failure: true
  #设置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB

  #redis 配置
  redis:
    host: 47.107.127.70
    port: 6379
    password: 123456
    database: 0 # Redis 数据库号，默认为 0 。
    timeout: 5000 # Redis 连接超时时间，单位：毫秒。
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 8 # 默认连接数最大空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制

  data:
    elasticsearch:
      cluster-nodes: 47.107.127.70:9300
      cluster-name: docker-cluster
      repositories:
        enabled: true

# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  #config-location: classpath*:mybatis/*.xml
  configuration:
    call-setters-on-nulls: true
# 七牛云配置
qiniu-cloud:
  access-key: -u69iismWnBYdOkGysrL_DEkGsR_A03BwmaIfVqG
  secret-key: RWoGxiF0wSPtPXF4KhqKC3Jorr056_Ux1fltGptS
  bucket: yang-blog-java-php
  domain: http://qbr6zdhq7.bkt.clouddn.com

# 阿里云短信配置
aliyun-dysmsapi:
  access-key-id: LTAIPQ0RwPDBknkE
  access-key-secret: UeY7zPs4HjWlnJT6qfebPZc9paTP5v
  sign-name: 潮品羊驼

logging:
  level:
    com.yang.blog: debug
debug: true